### ISSUE TITLE
Unnecessary log entry 'No monitoring event detected from:'

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-module-logs#23]
```
[2017-08-30 17:32:16 CEST] WARNING: [alignak.module.logs] No monitoring event detected from: ACTIVE SERVICE CHECK: localhost;Nrpe-status;OK;HARD;1;NRPE v2.15
```

**Comment by mohierf** [comment]
Those log are raised by Alignak (in *alignak.cfg*, `log_active_checks=1`, `log_passive_checks=1`) but the log module currently does not decode them correctly. 

I will publish very soon a version with this decoding.

**Comment by mohierf** [comment]
New version 0.5.4 correctly create a log for the active and passive checks
